version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: log3
    container_name: log3
    restart: unless-stopped
    working_dir: /var/www
    command: bash -c "composer install"
    volumes:
      - ${PWD}/:/var/www
      - ${PWD}/docker-config/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - caddy
    labels:
      caddy: log3.accesstechnology.co.uk
      caddy.root: "* $PWD/public"
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.php_fastcgi.root: /var/www/public
      caddy.encode: gzip
      caddy.file_server:

  vite:
    image: node:lts
    container_name: laravel_vite
    working_dir: /var/www
    command: sh -c "npm run prod"
    volumes:
      - ${PWD}/:/var/www

networks:
  caddy:
    external: true
